DROP DATABASE IF EXISTS burger_DB;
CREATE DATABASE burger_DB;

USE burger_DB;

CREATE TABLE burgers(
    id INTEGER AUTO_INCREMENT NOT NULL,
    name VARCHAR (225) NOT NULL,
    devoured BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);
